version: '3.8'

services:
  backend:
    build: 
      context: .
      dockerfile: backend/Dockerfile
    restart: always
    env_file: .env
    ports:
      - "8000:8000"
    volumes:
      - ./service_station.db:/app/service_station.db
      - ./logs:/app/logs
      - ./maps:/app/maps
    depends_on:
      - redis

  redis:
    image: redis:alpine
    restart: always