services:
  fastapi_server:
    build: ./
    # Команда для запуска FastAPI внутри контейнера
    command: uvicorn main:app --host 0.0.0.0 --port 8000
     
    environment:
      # Указываем путь к БД внутри контейнера для FastAPI
      - DATABASE_URL=sqlite:////app/database.db
    # Порт 8000 будет доступен ТОЛЬКО внутри сети Docker для бота. Снаружи сервера он закрыт.
    expose:
      - "8000"
    restart: always

  tg_bot:
    build: ./bot
    command: python bot.py
    env_file: .env
    depends_on:
      - redis
      - backend
    
    volumes:
      - ./logs:/app/logs
      - ./maps:/app/maps

  # Redis для Stateless FSM (чтобы не терять шаги пользователей)
  redis:
    image: redis:alpine
    restart: always 